### ISSUE TITLE
Create eventtarget failed

### ISSUE THREAD

**Issue by Xdydy** [apache/rocketmq-eventbridge#53]
When I create EventTarget to aliyun EventBridge it responses the logs as follows:

```text
Caused by: java.net.URISyntaxException: Illegal character in scheme name at index 0: 127.0.0.1:8082/connectors/1380866445961825-demo-bus-demo-rule-FC-target
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.checkChar(URI.java:3031)
	at java.net.URI$Parser.parse(URI.java:3047)
	at java.net.URI.<init>(URI.java:588)
	at org.apache.rocketmq.eventbridge.adapter.rpc.impl.connect.dto.CreateSinkConnectorRequest.getURI(CreateSinkConnectorRequest.java:51)
	at org.apache.rocketmq.eventbridge.adapter.rpc.impl.connect.RocketMQConnectClient.createSinkConnector(RocketMQConnectClient.java:85)
	at org.apache.rocketmq.eventbridge.adapter.rpc.impl.connect.RocketMQConnectTargetRunnerAPIImpl.createAndStartEventTargetRunner(RocketMQConnectTargetRunnerAPIImpl.java:55)
	at org.apache.rocketmq.eventbridge.domain.model.run.EventTargetRunnerService.createEventTargetRunner(EventTargetRunnerService.java:55)
	at org.apache.rocketmq.eventbridge.domain.model.target.EventTargetService.lambda$createTargets$0(EventTargetService.java:68)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.apache.rocketmq.eventbridge.domain.model.target.EventTargetService.createTargets(EventTargetService.java:60)
	at org.apache.rocketmq.eventbridge.domain.model.target.EventTargetService$$FastClassBySpringCGLIB$$9af371e3.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	... 130 common frames omitted
```

I want to reach the goal that when I produce the message to rocketmq it can transform the message to the eventtarget which I create before. Can you provide some document about the eventbridge API?

**Comment by 2011shenlin** [comment]
A RocketMQ Connect service is required here. Is this service deployed locally?  
You can refer to this document:
https://github.com/apache/rocketmq-eventbridge

and deploy the connect: https://github.com/apache/rocketmq-connect

**Comment by Xdydy** [comment]
> 

I am sure that I have deployed the connect service, because I have created the event source successfully. However this issue happened when I want to create event target

And I want to know that how I use the other API which demo doesn't provide. I see the repository didn't provide
